/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { StoryFindManyArgs } from "../../story/base/StoryFindManyArgs";
import { Story } from "../../story/base/Story";
import { StoryWhereUniqueInput } from "../../story/base/StoryWhereUniqueInput";
import { TaleCoinTransactionFindManyArgs } from "../../taleCoinTransaction/base/TaleCoinTransactionFindManyArgs";
import { TaleCoinTransaction } from "../../taleCoinTransaction/base/TaleCoinTransaction";
import { TaleCoinTransactionWhereUniqueInput } from "../../taleCoinTransaction/base/TaleCoinTransactionWhereUniqueInput";
import { WriterFindManyArgs } from "../../writer/base/WriterFindManyArgs";
import { Writer } from "../../writer/base/Writer";
import { WriterWhereUniqueInput } from "../../writer/base/WriterWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/stories")
  @ApiNestedQuery(StoryFindManyArgs)
  async findStories(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Story[]> {
    const query = plainToClass(StoryFindManyArgs, request.query);
    const results = await this.service.findStories(params.id, {
      ...query,
      select: {
        authorMimic: true,
        content: true,
        createdAt: true,
        genre: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stories")
  async connectStories(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stories")
  async updateStories(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stories")
  async disconnectStories(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/taleCoinTransactions")
  @ApiNestedQuery(TaleCoinTransactionFindManyArgs)
  async findTaleCoinTransactions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TaleCoinTransaction[]> {
    const query = plainToClass(TaleCoinTransactionFindManyArgs, request.query);
    const results = await this.service.findTaleCoinTransactions(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,
        date: true,
        id: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/taleCoinTransactions")
  async connectTaleCoinTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TaleCoinTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      taleCoinTransactions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/taleCoinTransactions")
  async updateTaleCoinTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TaleCoinTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      taleCoinTransactions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/taleCoinTransactions")
  async disconnectTaleCoinTransactions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TaleCoinTransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      taleCoinTransactions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/writers")
  @ApiNestedQuery(WriterFindManyArgs)
  async findWriters(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Writer[]> {
    const query = plainToClass(WriterFindManyArgs, request.query);
    const results = await this.service.findWriters(params.id, {
      ...query,
      select: {
        bio: true,
        createdAt: true,
        id: true,
        profilePicture: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/writers")
  async connectWriters(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WriterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      writers: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/writers")
  async updateWriters(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WriterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      writers: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/writers")
  async disconnectWriters(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WriterWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      writers: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
